stages:
    - test-python
    - build-docs

python3_5_unit_test:
  image: seriallab/python3.5dev
  stage: test-python
  script:
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install -r requirements.txt
  - pip install coverage
  - cd EPCPyYes/core/tests/
  - coverage run -m unittest discover
  - coverage report -m
  - coverage html
  artifacts:
    paths:
      - EPCPyYes/core/tests/htmlcov/

pages:
    image: seriallab/python3.5dev
    stage: build-docs
    script:
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
    - pip install sphinx recommonmark sphinx_rtd_theme pygments ipython
    - make html --directory=docs/api
    - mv docs/api/_build/html/ public/
    artifacts:
        paths:
        - public
    only:
      - master